spring.application.name=vinyle

##MONGO
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=vinyle_db
spring.data.mongodb.username=julien
spring.data.mongodb.password=1234
spring.data.mongodb.authentication-database=admin

##Bruno
app.jwt.test-token=1234567890-test-token

